<body>
  <div id="root"></div>
  <script src="https://unpkg.com/react@16.12.0/umd/react.production.min.js"></script>
  <script src="https://unpkg.com/react-dom@16.12.0/umd/react-dom.production.min.js"></script>
  <script src="https://unpkg.com/@babel/standalone@7.8.3/babel.js"></script>
  <script src="https://unpkg.com/react-error-boundary@1.2.5/dist/umd/react-error-boundary.js"></script>
  <script type="text/babel">
    const rootElement = document.getElementById("root");

    // class ErrorBoundary extends React.Component {
    //   state = { error: null };

    //   static getDerivedStateFromError(error) {
    //     return { error };
    //   }

    //   render() {
    //     const { error } = this.state;
    //     if (error) {
    //       return <this.props.FallbackComponent error={error} />;
    //     }
    //     return this.props.children;
    //   }
    // }

    const ErrorBoundary = ReactErrorBoundary.ErrorBoundary;

    function ErrorFallback({ error }) {
      return (
        <div>
          <p>Something went wrong:</p>
          <pre>{error.message}</pre>
        </div>
      );
    }

    function Bomb() {
      throw Error("ðŸ’¥ CABOOM ðŸ’¥");
    }

    function App() {
      const [explode, setExplode] = React.useState(() => false);

      return (
        <div>
          <div>
            <button onClick={() => setExplode(true)}>ðŸ’£</button>
          </div>
          <div>
            <ErrorBoundary FallbackComponent={ErrorFallback}>
              {explode ? <Bomb /> : "Push the button"}
            </ErrorBoundary>
          </div>
        </div>
      );
    }

    ReactDOM.render(<App />, rootElement);
  </script>
</body>
